name: test

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'

# Only cancel in-progress jobs or runs for the current workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Build in ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Development Containers
        uses: devcontainers/ci@v0.2.1900000215
      - run: npm run test
