name: Proofreading

on:
  pull_request:
    branches:
      - main
    paths:
      - '.devcontainer/**'
      - '.github/workflows/proofreading.yml'
      - 'articles/*.md'
      - 'books/**/*.md'
      - 'package.json'
      - 'package-lock.json'

# Only cancel in-progress jobs or runs for the current workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  textlint:
    name: Check from Textlint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f #v1.5.0
        with:
          reviewdog_version: latest

      - name: Run Dev Container
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca #v0.3.1900000450
        with:
          configFile: "./.devcontainer/devcontainer.json"
          runCmd: npx textlint -f checkstyle './{articles,books}/*.md' >> .textlint.log

      - name: Run reviewdog
        if: failure()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat .textlint.log | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
