name: Zenn meta check

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/zenn-meta-check.yml'
      - '**.md'
      - 'package.json'
      - 'package-lock.json'


# Only cancel in-progress jobs or runs for the current workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  textlint:
    name: Check Zenn metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vallidate metadata
        uses: korosuke613/zenn-metadata-updater-action@v2
        with:
            dry-run: true
            validate-only: true
